### ISSUE TITLE
Mod Crashes During Birth Event

### ISSUE THREAD

**Issue by star444de222** [nofilenamed/FamilyPlanningMod#1]
I tried this out. I was looking for a mod that would allow me to have more than 2 kids with my 4 spouses. When I enter the commands into SMAPI, it seems to work just fine. I was asked by one of my spouses if I wanted to have a baby the following night. I did however get weird warnings in SMAPI whenever the game booted up. This did not affect my gameplay or save file at all. 

Here is my smapi log: https://smapi.io/log/693d8096f87b40068a9399dba9667809

Thanks!

Update: After being asked by spouse if I wanted to have a baby, the birth event triggered 14 days later. The baby name/gender select screen was pretty messed up though. I took a screenshot. After I entered the name and clicked enter, the mod caused my game to crash. Luckily, there was no damage done to the save file. I tested it one more time and it crashed after I named the baby and save. Seems like this is as far as the mod can run before crashing. 

Workaround: since the mod crashes, I removed it, but I was happy to find that the birth event will still take place even with the mod removed (guess because the player is still pregnant). So there is still the benefit of the mod allowing the player to have more than 2 kids from different spouses, even if it must be removed after asking the baby question. 

Here is my smapi log: https://smapi.io/log/2d4a79d3cc0a49c68f69e8983f1ecc5a

![image](https://github.com/nofilenamed/FamilyPlanningMod/assets/170834749/7638f011-8800-4e75-beff-dbbe644bc4d1)

**Comment by nofilenamed** [comment]
Should work better now. Feel free to try it out. Version 2.0.1 is out for download.

**Comment by star444de222** [comment]
> Should work better now. Feel free to try it out. Version 2.0.1 is out for download.

Thanks! Trying it now. Will you be uploading this to nexus mods when it is complete?

**Comment by nofilenamed** [comment]
Maybe, but I have to handle the support. Why wouldn't you upload this to Nexus?
